---
version: 2
defaults: &defaults
  working_directory: /home/circleci/algo
  machine:
    image: ubuntu-1604:201903-01
workflows:
  version: 2
  checkout_run_test:
    jobs:
      - checkout
      - arch64:
          requires:
            - checkout
      - test-arch64:
          requires:
            - checkout
      - ubuntu64:
          requires:
            - checkout
      - test-ubuntu64:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root:  .
          paths: .
  arch64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make arch64
  test-arch64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-arch64
  ubuntu64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make ubuntu64
  test-ubuntu64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-ubuntu64
